version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: book-library-api/src/BookLibrary.API/Dockerfile
    extends:
      file: docker-compose.settings.yaml
      service: appsettings
    depends_on:
      - sql-server
      - rabbitmq
    ports:
      - 5262:8080

  reports:
    build:
      context: .
      dockerfile: book-library-api/src/BookLibrary.Reports/Dockerfile
    extends:
      file: docker-compose.settings.yaml
      service: appsettings
    depends_on:
      - sql-server
      - rabbitmq

  client:
    build: ./book-library-client
    container_name: book-library-client
    ports:
      - 3000:3000

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=RabbitMQ3!
      - RABBITMQ_DEFAULT_VHOST=docker
    ports:
      - 5672:5672
      - 15672:15672

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "SqlServer2022!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  mssql-tools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sql-server
    volumes:
      - ./mssql-tools-commands.sh:/tmp/mssql-tools-commands.sh
      - ./book-library-api/src/BookLibrary.Infra/Scripts:/tmp/Scripts
    command: /bin/bash ./tmp/mssql-tools-commands.sh