# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- none

resources:
- repo: self

pool:
  vmImage: $(vmImageName)

extends:
  template: azure-pipelines-base.yml
  parameters:
    imageRepository: 'netcore-reports-image'
    deploymentFileName: 'netcore-reports-deployment.yaml'
    dockerfilePath: '$(Build.SourcesDirectory)/book-library-api/src/BookLibrary.Reports/Dockerfile'
