apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-client
  template:
    metadata:
      labels:
        app: react-client
    spec:
      containers:
      - name: react-client
        image: booklibraryacr.azurecr.io/react-client-image:$(Build.BuildId)
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react-client-service
spec:
  type: NodePort
  selector:
    app: react-client
  ports:
  - name: react-client-service
    port: 3000
    targetPort: 3000