apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-client
  template:
    metadata:
      labels:
        app: react-client
    spec:
      containers:
      - name: react-client
        image: booklibraryacr.azurecr.io/react-client-image:$(Build.BuildId)
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "0.5"
            memory: "1Gi"
        env:
        - name: VITE_API_HOST
          value: $(API_HOST)
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react-client-service
spec:
  type: LoadBalancer
  selector:
    app: react-client
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP